<?php
// Heading
$_['heading_title']              = 'Products';

// Text
$_['text_success']               = 'Success: You have modified products!';
$_['text_variant']               = 'Please note because this is a variant product you must override the <a href="%s" target="_blank" class="alert-link">master product</a> data. Otherwise the data will get replaced with the <a href="%s" target="_blank" class="alert-link">master product</a> data when saved.';
$_['text_list']                  = 'Product List';
$_['text_add']                   = 'Add Product';
$_['text_edit']                  = 'Edit Product';
$_['text_variant_add']           = 'Add Variant';
$_['text_general']               = 'General';
$_['text_meta']                  = 'Meta Tags';
$_['text_model']                 = 'Model';
$_['text_price']                 = 'Price';
$_['text_stock']                 = 'Stock';
$_['text_specification']         = 'Specification';
$_['text_filter']                = 'Filter';
$_['text_keyword']               = 'Do not use spaces, instead replace spaces with - and make sure the SEO URL is globally unique.';
$_['text_option_add']            = 'Add Option';
$_['text_option_value']          = 'Option Value';
$_['text_select']                = 'Select';
$_['text_radio']                 = 'Radio';
$_['text_checkbox']              = 'Checkbox';
$_['text_input']                 = 'Input';
$_['text_text']                  = 'Text';
$_['text_textarea']              = 'Textarea';
$_['text_file']                  = 'File';
$_['text_date']                  = 'Date';
$_['text_datetime']              = 'Date &amp; Time';
$_['text_time']                  = 'Time';
$_['text_fixed']                 = 'Fixed Amount';
$_['text_subtract']              = 'Subtract';
$_['text_percentage']            = 'Percentage';
$_['text_image']                 = 'Image';
$_['text_image_additional']      = 'Additional Images';
$_['text_reward']                = 'Buy Points';
$_['text_points']                = 'Reward Points';
$_['text_from']                  = 'From';
$_['text_to']                    = 'To';
$_['text_subscription_trial']    = '<x-currency code="%s" amount="%f"></x-currency> every %d %s(s) for %d payment(s) then ';
$_['text_subscription_duration'] = '<x-currency code="%s" amount="%f"></x-currency> every %d %s(s) for %d payment(s)';
$_['text_subscription_cancel']   = '<x-currency code="%s" amount="%f"></x-currency> every %d %s(s) until canceled';
$_['text_day']                   = 'day';
$_['text_week']                  = 'week';
$_['text_semi_month']            = 'half-month';
$_['text_month']                 = 'month';
$_['text_year']                  = 'year';
$_['text_report']                = 'Reports';

// Column
$_['column_name']                = 'Product Name';
$_['column_model']               = 'Model';
$_['column_image']               = 'Image';
$_['column_price']               = 'Price';
$_['column_quantity']            = 'Quantity';
$_['column_status']              = 'Status';
$_['column_ip']                  = 'IP';
$_['column_store']               = 'Store';
$_['column_country']             = 'Country';
$_['column_date_added']          = 'Date Added';
$_['column_action']              = 'Action';

// Entry
$_['entry_name']                 = 'Product Name';
$_['entry_description']          = 'Description';
$_['entry_meta_title']           = 'Meta Tag Title';
$_['entry_meta_keyword']         = 'Meta Tag Keywords';
$_['entry_meta_description']     = 'Meta Tag Description';
$_['entry_store']                = 'Stores';
$_['entry_keyword']              = 'Keyword';
$_['entry_model']                = 'Model';
$_['entry_product_code']         = 'Product Codes';
$_['entry_location']             = 'Location';
$_['entry_shipping']             = 'Requires Shipping';
$_['entry_manufacturer']         = 'Manufacturer';
$_['entry_date_available']       = 'Date Available';
$_['entry_quantity']             = 'Quantity';
$_['entry_minimum']              = 'Minimum Quantity';
$_['entry_stock_status']         = 'Out Of Stock Status';
$_['entry_price']                = 'Price';
$_['entry_trial_price']          = 'Trial Price';
$_['entry_tax_class']            = 'Tax Class';
$_['entry_points']               = 'Points';
$_['entry_subtract']             = 'Subtract Stock';
$_['entry_weight_class']         = 'Weight Class';
$_['entry_weight']               = 'Weight';
$_['entry_dimension']            = 'Dimensions (L x W x H)';
$_['entry_length_class']         = 'Length Class';
$_['entry_length']               = 'Length';
$_['entry_width']                = 'Width';
$_['entry_height']               = 'Height';
$_['entry_option']               = 'Option';
$_['entry_option_value']         = 'Option Value';
$_['entry_customer_group']       = 'Customer Group';
$_['entry_special']              = 'Special';
$_['entry_type']                 = 'Type';
$_['entry_date_start']           = 'Date Start';
$_['entry_date_end']             = 'Date End';
$_['entry_priority']             = 'Priority';
$_['entry_attribute']            = 'Attribute';
$_['entry_attribute_group']      = 'Attribute Group';
$_['entry_image']                = 'Image';
$_['entry_text']                 = 'Text';
$_['entry_required']             = 'Required';
$_['entry_status']               = 'Status';
$_['entry_sort_order']           = 'Sort Order';
$_['entry_category']             = 'Categories';
$_['entry_filter']               = 'Filters';
$_['entry_download']             = 'Downloads';
$_['entry_related']              = 'Related Products';
$_['entry_tag']                  = 'Product Tags';
$_['entry_reward']               = 'Reward Points';
$_['entry_layout']               = 'Layout Override';
$_['entry_subscription']         = 'Subscription Plan';

// Help
$_['help_tag']                   = 'Comma separated';
$_['help_minimum']               = 'Force a minimum ordered amount';
$_['help_stock_status']          = 'Status shown when a product is out of stock';
$_['help_manufacturer']          = '(Autocomplete)';
$_['help_category']              = '(Autocomplete)';
$_['help_filter']                = '(Autocomplete)';
$_['help_download']              = '(Autocomplete)';
$_['help_related']               = '(Autocomplete)';
$_['help_option']                = '(Autocomplete)';
$_['help_points']                = 'Number of points needed to buy this item. If you don\'t want this product to be purchased with points leave as 0.';

// Error
$_['error_warning']              = 'Warning: Please check the form carefully for errors!';
$_['error_permission']           = 'Warning: You do not have permission to modify products!';
$_['error_name']                 = 'Product Name must be greater than 1 and less than 255 characters!';
$_['error_meta_title']           = 'Meta Title must be greater than 1 and less than 255 characters!';
$_['error_model']                = 'Product Model must be greater than 1 and less than 64 characters!';
$_['error_keyword']              = 'SEO URL must be between 1 and 64 characters!';
$_['error_keyword_exists']       = 'SEO URL must be unique!';
$_['error_keyword_character']    = 'Keyword can only use characters a-z, 0-9, - and _!';
$_['error_required']             = '%s required!';
$_['error_regex']                = '%s is not a valid input!';