<?php
/**
 * @package		OpenCart
 *
 * @author		Daniel Kerr
 * @copyright	Copyright (c) 2005 - 2022, OpenCart, Ltd. (https://www.opencart.com/)
 * @license		https://opensource.org/licenses/GPL-3.0
 *
 * @see		https://www.opencart.com
 */
namespace Opencart\System\Engine;
/**
 * Class Registry
 *
 * Loaded during application bootup
 *
 * @property \Opencart\System\Engine\Autoloader     $autoloader
 * @property \Opencart\System\Engine\Config         $config
 * @property \Opencart\System\Engine\Event          $event
 * @property \Opencart\System\Engine\Factory        $factory
 * @property \Opencart\System\Engine\Loader         $load
 * @property \Opencart\System\Library\Cache         $cache
 * @property \Opencart\System\Library\Cart\Cart     $cart
 * @property \Opencart\System\Library\Cart\Currency $currency
 * @property \Opencart\System\Library\Cart\Customer $customer
 * @property \Opencart\System\Library\Cart\Length   $length
 * @property \Opencart\System\Library\Cart\Tax      $tax
 * @property \Opencart\System\Library\Cart\Weight   $weight
 * @property \Opencart\System\Library\DB            $db
 * @property \Opencart\System\Library\Document      $document
 * @property \Opencart\System\Library\Language      $language
 * @property \Opencart\System\Library\Log           $log
 * @property \Opencart\System\Library\Request       $request
 * @property \Opencart\System\Library\Response      $response
 * @property \Opencart\System\Library\Session       $session
 * @property \Opencart\System\Library\Template      $template
 * @property \Opencart\System\Library\Url           $url
 *
 * Loaded during login
 * @property ?\Opencart\System\Library\Cart\User $user
 *
 * Model keys generated by: php tools/generate_registry_docblock.php
 * -- BEGIN GENERATED MODEL PROPERTIES --
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Activity>|null                                                                                                               $model_account_activity
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Address>|null                                                                                                                $model_account_address
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Affiliate>|null                                                                                                              $model_account_affiliate
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Approval>|null                                                                                                               $model_account_approval
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\CustomField>|null                                                                                                            $model_account_custom_field
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Customer>|null                                                                                                               $model_account_customer
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\CustomerGroup>|null                                                                                                          $model_account_customer_group
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Download>|null                                                                                                               $model_account_download
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Gdpr>|null                                                                                                                   $model_account_gdpr
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Order>|null                                                                                                                  $model_account_order
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Returns>|null                                                                                                                $model_account_returns
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Reward>|null                                                                                                                 $model_account_reward
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Search>|null                                                                                                                 $model_account_search
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Subscription>|null                                                                                                           $model_account_subscription
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Transaction>|null                                                                                                            $model_account_transaction
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Account\Wishlist>|null                                                                                                               $model_account_wishlist
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Attribute>|null                                                                                                                $model_catalog_attribute
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\AttributeGroup>|null                                                                                                           $model_catalog_attribute_group
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Category>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Catalog\Category>|null                                         $model_catalog_category
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Download>|null                                                                                                                 $model_catalog_download
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Filter>|null                                                                                                                   $model_catalog_filter
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\FilterGroup>|null                                                                                                              $model_catalog_filter_group
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Identifier>|null                                                                                                               $model_catalog_identifier
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Information>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Catalog\Information>|null                                   $model_catalog_information
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Manufacturer>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Catalog\Manufacturer>|null                                 $model_catalog_manufacturer
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Option>|null                                                                                                                   $model_catalog_option
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Product>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Catalog\Product>|null                                           $model_catalog_product
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\Review>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Catalog\Review>|null                                             $model_catalog_review
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Catalog\SubscriptionPlan>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Catalog\SubscriptionPlan>|null                         $model_catalog_subscription_plan
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Checkout\Cart>|null                                                                                                                  $model_checkout_cart
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Checkout\Order>|null                                                                                                                 $model_checkout_order
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Checkout\PaymentMethod>|null                                                                                                         $model_checkout_payment_method
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Checkout\ShippingMethod>|null                                                                                                        $model_checkout_shipping_method
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Checkout\Subscription>|null                                                                                                          $model_checkout_subscription
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Cms\Antispam>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Cms\Antispam>|null                                                 $model_cms_antispam
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Cms\Article>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Cms\Article>|null                                                   $model_cms_article
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Cms\Topic>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Cms\Topic>|null                                                       $model_cms_topic
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Customer\CustomField>|null                                                                                                             $model_customer_custom_field
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Customer\Customer>|null                                                                                                                $model_customer_customer
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Customer\CustomerApproval>|null                                                                                                        $model_customer_customer_approval
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Customer\CustomerGroup>|null                                                                                                           $model_customer_customer_group
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Customer\Gdpr>|null                                                                                                                    $model_customer_gdpr
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Design\Banner>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Design\Banner>|null                                               $model_design_banner
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Design\Layout>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Design\Layout>|null                                               $model_design_layout
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Design\SeoUrl>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Design\SeoUrl>|null                                               $model_design_seo_url
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Design\Theme>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Design\Theme>|null                                                 $model_design_theme
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Design\Translation>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Design\Translation>|null                                     $model_design_translation
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Dashboard\Map>|null                                                                                                 $model_extension_opencart_dashboard_map
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Fraud\Ip>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Fraud\Ip>|null                   $model_extension_opencart_fraud_ip
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Module\Bestseller>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Module\Bestseller>|null $model_extension_opencart_module_bestseller
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Module\Blog>|null                                                                                                 $model_extension_opencart_module_blog
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Module\Latest>|null                                                                                               $model_extension_opencart_module_latest
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Other\Cloud>|null                                                                                                   $model_extension_opencart_other_cloud
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Payment\BankTransfer>|null                                                                                        $model_extension_opencart_payment_bank_transfer
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Payment\Cheque>|null                                                                                              $model_extension_opencart_payment_cheque
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Payment\COD>|null                                                                                                 $model_extension_opencart_payment_cod
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Payment\FreeCheckout>|null                                                                                        $model_extension_opencart_payment_free_checkout
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\Activity>|null                                                                                               $model_extension_opencart_report_activity
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\Coupon>|null                                                                                                 $model_extension_opencart_report_coupon
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\Customer>|null                                                                                               $model_extension_opencart_report_customer
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\CustomerTransaction>|null                                                                                    $model_extension_opencart_report_customer_transaction
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\Marketing>|null                                                                                              $model_extension_opencart_report_marketing
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\ProductPurchased>|null                                                                                       $model_extension_opencart_report_product_purchased
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\ProductViewed>|null                                                                                          $model_extension_opencart_report_product_viewed
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\Returns>|null                                                                                                $model_extension_opencart_report_returns
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\Sale>|null                                                                                                   $model_extension_opencart_report_sale
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Extension\Opencart\Report\Subscription>|null                                                                                           $model_extension_opencart_report_subscription
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Shipping\Flat>|null                                                                                               $model_extension_opencart_shipping_flat
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Shipping\Free>|null                                                                                               $model_extension_opencart_shipping_free
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Shipping\Item>|null                                                                                               $model_extension_opencart_shipping_item
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Shipping\Pickup>|null                                                                                             $model_extension_opencart_shipping_pickup
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Shipping\Weight>|null                                                                                             $model_extension_opencart_shipping_weight
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\Coupon>|null                                                                                                $model_extension_opencart_total_coupon
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\Credit>|null                                                                                                $model_extension_opencart_total_credit
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\Handling>|null                                                                                              $model_extension_opencart_total_handling
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\LowOrderFee>|null                                                                                           $model_extension_opencart_total_low_order_fee
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\Reward>|null                                                                                                $model_extension_opencart_total_reward
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\Shipping>|null                                                                                              $model_extension_opencart_total_shipping
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\SubTotal>|null                                                                                              $model_extension_opencart_total_sub_total
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\Tax>|null                                                                                                   $model_extension_opencart_total_tax
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Extension\Opencart\Total\Total>|null                                                                                                 $model_extension_opencart_total_total
 * @property \Opencart\System\Engine\Proxy<\Opencart\Install\Model\Install\Install>|null                                                                                                                $model_install_install
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\AddressFormat>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\AddressFormat>|null                     $model_localisation_address_format
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\Country>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\Country>|null                                 $model_localisation_country
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\Currency>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\Currency>|null                               $model_localisation_currency
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\GeoZone>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\GeoZone>|null                                 $model_localisation_geo_zone
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\Language>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\Language>|null                               $model_localisation_language
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\LengthClass>|null                                                                                                         $model_localisation_length_class
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\Location>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\Location>|null                               $model_localisation_location
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\OrderStatus>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\OrderStatus>|null                         $model_localisation_order_status
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\ReturnAction>|null                                                                                                        $model_localisation_return_action
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\ReturnReason>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\ReturnReason>|null                       $model_localisation_return_reason
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\ReturnStatus>|null                                                                                                        $model_localisation_return_status
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\StockStatus>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\StockStatus>|null                         $model_localisation_stock_status
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\SubscriptionStatus>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\SubscriptionStatus>|null           $model_localisation_subscription_status
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\TaxClass>|null                                                                                                            $model_localisation_tax_class
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\TaxRate>|null                                                                                                             $model_localisation_tax_rate
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\WeightClass>|null                                                                                                         $model_localisation_weight_class
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Localisation\Zone>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Localisation\Zone>|null                                       $model_localisation_zone
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Marketing\Affiliate>|null                                                                                                              $model_marketing_affiliate
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Marketing\Coupon>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Marketing\Coupon>|null                                         $model_marketing_coupon
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Marketing\Marketing>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Marketing\Marketing>|null                                   $model_marketing_marketing
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Report\Online>|null                                                                                                                    $model_report_online
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Report\Statistics>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Report\Statistics>|null                                       $model_report_statistics
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Sale\Order>|null                                                                                                                       $model_sale_order
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Sale\Returns>|null                                                                                                                     $model_sale_returns
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Sale\Subscription>|null                                                                                                                $model_sale_subscription
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Setting\Api>|null                                                                                                                    $model_setting_api
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Setting\Cron>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Setting\Cron>|null                                                 $model_setting_cron
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Setting\Event>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Setting\Event>|null                                               $model_setting_event
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Setting\Extension>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Setting\Extension>|null                                       $model_setting_extension
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Setting\Modification>|null                                                                                                             $model_setting_modification
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Setting\Module>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Setting\Module>|null                                             $model_setting_module
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Setting\Setting>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Setting\Setting>|null                                           $model_setting_setting
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Setting\Startup>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Setting\Startup>|null                                           $model_setting_startup
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Setting\Store>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Setting\Store>|null                                               $model_setting_store
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Tool\Backup>|null                                                                                                                      $model_tool_backup
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Tool\Image>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Tool\Image>|null                                                     $model_tool_image
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Tool\Notification>|null                                                                                                                $model_tool_notification
 * @property \Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Tool\Online>|null                                                                                                                    $model_tool_online
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\Tool\Upload>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\Tool\Upload>|null                                                   $model_tool_upload
 * @property \Opencart\System\Engine\Proxy<\Opencart\Install\Model\Upgrade\Upgrade>|null                                                                                                                $model_upgrade_upgrade
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\User\Api>|\Opencart\System\Engine\Proxy<\Opencart\Catalog\Model\User\Api>|null                                                         $model_user_api
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\User\User>|null                                                                                                                        $model_user_user
 * @property \Opencart\System\Engine\Proxy<\Opencart\Admin\Model\User\UserGroup>|null                                                                                                                   $model_user_user_group
 *
 * -- END GENERATED MODEL PROPERTIES --
 */
class Registry {
	/**
	 * @var array<string, object>
	 */
	private array $data = [];

	/**
	 * __get
	 *
	 * https://www.php.net/manual/en/language.oop5.overloading.php#object.get
	 *
	 * @param string $key
	 *
	 * @return ?object
	 */
	public function __get(string $key): ?object {
		return $this->get($key);
	}

	/**
	 * __set
	 *
	 * https://www.php.net/manual/en/language.oop5.overloading.php#object.set
	 *
	 * @param string $key
	 * @param object $value
	 *
	 * @return void
	 */
	public function __set(string $key, object $value): void {
		$this->set($key, $value);
	}

	/**
	 * __isset
	 *
	 * https://www.php.net/manual/en/language.oop5.overloading.php#object.set
	 *
	 * @param string $key
	 *
	 * @return bool
	 */
	public function __isset(string $key): bool {
		return $this->has($key);
	}

	/**
	 * Get
	 *
	 * @param string $key
	 *
	 * @return ?object
	 */
	public function get(string $key): ?object {
		return $this->data[$key] ?? null;
	}

	/**
	 * Set
	 *
	 * @param string $key
	 * @param object $value
	 *
	 * @return void
	 */
	public function set(string $key, object $value): void {
		$this->data[$key] = $value;
	}

	/**
	 * Has
	 *
	 * @param string $key
	 *
	 * @return bool
	 */
	public function has(string $key): bool {
		return isset($this->data[$key]);
	}

	/**
	 * Unset
	 *
	 * Unsets registry value by key.
	 *
	 * @param string $key
	 *
	 * @return void
	 */
	public function unset(string $key): void {
		unset($this->data[$key]);
	}
}
