<?php
// Heading
$_['heading_title']              = 'Produkte';

// Text
$_['text_success']               = 'Erfolgreich: Sie haben Produkte geändert!';
$_['text_variant']               = 'Bitte beachten Sie, dass Sie die Daten des <a href="%s" target="_blank" class="alert-link">Hauptprodukts</a> überschreiben müssen, da es sich hier um ein Variantenprodukt handelt. Andernfalls werden die Daten beim Speichern durch die Daten des <a href="%s" target="_blank" class="alert-link">Hauptprodukts</a> ersetzt.';
$_['text_list']                  = 'Produkt Liste';
$_['text_add']                   = 'Neues Produkt zufügen';
$_['text_edit']                  = 'Produkt bearbeiten';
$_['text_variant_add']           = 'Variante zufügen';
$_['text_model']                 = 'Modell';
$_['text_price']                 = 'Preis';
$_['text_stock']                 = 'Aktie';
$_['text_specification']         = 'Spezifikation';
$_['text_filter']                = 'Filter';
$_['text_default']               = 'Standard';
$_['text_keyword']               = 'Verwenden Sie keine Leerzeichen, ersetzen Sie Leerzeichen stattdessen durch - und stellen Sie sicher, dass die SEO-URL  eindeutig ist.';
$_['text_option_add']            = 'Neue Option zufügen';
$_['text_option_value']          = 'Optionswert';
$_['text_select']                = 'Select';
$_['text_radio']                 = 'Radio';
$_['text_checkbox']              = 'Checkbox';
$_['text_input']                 = 'Eingabe';
$_['text_text']                  = 'Text';
$_['text_textarea']              = 'Textbereich';
$_['text_file']                  = 'Datei';
$_['text_date']                  = 'Datum';
$_['text_datetime']              = 'Datum &amp; Uhrzeit';
$_['text_time']                  = 'Zeit';
$_['text_fixed']                 = 'Fester Betrag';
$_['text_subtract']              = 'Subtrahieren';
$_['text_percentage']            = 'Prozentsatz';
$_['text_image']                 = 'Bild';
$_['text_image_additional']      = 'Weitere Bilder';
$_['text_reward']                = 'Punkte kaufen';
$_['text_points']                = 'Belohnungspunkte';
$_['text_from']                  = 'Aus';
$_['text_to']                    = 'Zu';
$_['text_subscription_trial']    = '%s alle %d %s(s) für %d Zahlung(en) dann ';
$_['text_subscription_duration'] = '%s alle %d %s(s) für %d Zahlung(en)';
$_['text_subscription_cancel']   = '%s alle %d %s(s) bis zum Abbruch';
$_['text_day']                   = 'Tag';
$_['text_week']                  = 'Woche';
$_['text_semi_month']            = 'Halber Monat';
$_['text_month']                 = 'Monat';
$_['text_year']                  = 'Jahr';
$_['text_report']                = 'Berichte';

// Column
$_['column_name']                = 'Produkt Name';
$_['column_model']               = 'Modell';
$_['column_image']               = 'Bild';
$_['column_price']               = 'Preis';
$_['column_quantity']            = 'Menge';
$_['column_status']              = 'Status';
$_['column_ip']                  = 'IP';
$_['column_store']               = 'Online-Shop (Store)';
$_['column_country']             = 'Land';
$_['column_date_added']          = 'Datum hinzugefügt';
$_['column_action']              = 'Aktionen';

// Entry
$_['entry_name']                 = 'Produkt Name';
$_['entry_description']          = 'Beschreibung';
$_['entry_meta_title']           = 'Meta-Tag-Titel';
$_['entry_meta_keyword']         = 'Meta-Tag-Schlüsselwörter';
$_['entry_meta_description']     = 'Meta-Tag-Beschreibung';
$_['entry_store']                = 'Online-Shop (Store)';
$_['entry_keyword']              = 'SEO-URL Kennung (Schlüsselwort)';
$_['entry_model']                = 'Modell';
$_['entry_product_code']         = 'Produktcodes';
$_['entry_location']             = 'Standort';
$_['entry_shipping']             = 'Erfordert Versand';
$_['entry_manufacturer']         = 'Hersteller';
$_['entry_date_available']       = 'Verfügbares Datum';
$_['entry_quantity']             = 'Menge';
$_['entry_minimum']              = 'Mindestmenge';
$_['entry_stock_status']         = 'Nicht auf Lager';
$_['entry_price']                = 'Preis';
$_['entry_trial_price']          = 'Testpreis';
$_['entry_tax_class']            = 'Steuerklasse';
$_['entry_points']               = 'Punkte';
$_['entry_subtract']             = 'Bestand abziehen';
$_['entry_weight_class']         = 'Gewichtsklasse';
$_['entry_weight']               = 'Gewicht';
$_['entry_dimension']            = 'Abmessungen (L x B x H)';
$_['entry_length_class']         = 'Längenklasse';
$_['entry_length']               = 'Länge';
$_['entry_width']                = 'Breite';
$_['entry_height']               = 'Höhe';
$_['entry_option']               = 'Option';
$_['entry_option_value']         = 'Optionswert';
$_['entry_customer_group']       = 'Kundengruppe';
$_['entry_special']              = 'Besonders';
$_['entry_type']                 = 'Typ';
$_['entry_date_start']           = 'Datum Beginn';
$_['entry_date_end']             = 'Datum Ende';
$_['entry_priority']             = 'Priorität';
$_['entry_attribute']            = 'Attribut';
$_['entry_attribute_group']      = 'Eigenschaften-Gruppe';
$_['entry_image']                = 'Bild';
$_['entry_text']                 = 'Text';
$_['entry_required']             = 'Erforderlich';
$_['entry_status']               = 'Status';
$_['entry_sort_order']           = 'Sortierreihenfolge';
$_['entry_category']             = 'Kategorien';
$_['entry_filter']               = 'Filter';
$_['entry_download']             = 'Downloads';
$_['entry_related']              = 'Verwandte Produkte';
$_['entry_tag']                  = 'Produkt Tags';
$_['entry_reward']               = 'Belohnungspunkte';
$_['entry_layout']               = 'Layout überschreiben';
$_['entry_subscription']         = 'Abonnementplan';

// Help
$_['help_tag']                   = 'Durch Komma getrennt';
$_['help_minimum']               = 'Erzwingen Sie eine Mindestbestellmenge';
$_['help_stock_status']          = 'Status, der angezeigt wird, wenn ein Produkt nicht vorrätig ist';
$_['help_manufacturer']          = '(Autovervollständigung)';
$_['help_category']              = '(Autovervollständigung)';
$_['help_filter']                = '(Autovervollständigung)';
$_['help_download']              = '(Autovervollständigung)';
$_['help_related']               = '(Autovervollständigung)';
$_['help_option']                = '(Autovervollständigung)';
$_['help_points']                = 'Anzahl der Punkte, die zum Kauf dieses Artikels erforderlich sind. Wenn Sie dieses Produkt nicht mit Punkten kaufen möchten, lassen Sie den Wert auf 0.';

// Error
$_['error_warning']              = 'Warnung: Bitte prüfen Sie das Formular sorgfältig auf Fehler!';
$_['error_permission']           = 'Achtung: Sie sind nicht berechtigt, Produkte zu ändern!';
$_['error_name']                 = 'Der Produktname muss größer als 1 und kleiner als 255 Zeichen sein!';
$_['error_meta_title']           = 'Der Meta-Titel muss größer als 1 und kleiner als 255 Zeichen sein!';
$_['error_model']                = 'Das Produktmodell muss größer als 1 und kleiner als 64 Zeichen sein!';
$_['error_keyword']              = 'Die SEO-URL muss zwischen 1 und 64 Zeichen lang sein!';
$_['error_keyword_exists']       = 'SEO-URL muss eindeutig sein!';
$_['error_keyword_character']    = 'Das Schlüsselwort darf nur die Zeichen az, 0-9, - und _ enthalten!';
$_['error_required']             = '%s erforderlich!';
