# Text
text_compare: 'Product Compare (%s)'
text_sort: 'Sort By'
text_price: 'Price'
text_latest: 'Latest'
text_popularity: 'Popularity'
text_rating: 'Rating'
text_asc: 'Ascending'
text_desc: 'Descending'
text_limit: 'Show'
text_no_results: 'There are no products to list.'